// Copyright 2025 contributors to the GeoPlegmata project.
// Originally authored by Michael Jendryke, GeoInsight (michael.jendryke@geoinsight.ai)
//
// Licenced under the Apache Licence, Version 2.0 <LICENCE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENCE-MIT or http://opensource.org/licenses/MIT>, at your
// discretion. This file may not be copied, modified, or distributed
// except according to those terms.

use crate::types::{
    DggrsImplementation, DggrsName, DggrsSpec, DggrsUid, RefinementLevel, RelativeDepth,
};
pub const DGGRS_SPECS: [DggrsSpec; 11] = [
    DggrsSpec {
        id: DggrsUid::ISEA3HDGGRID,
        name: DggrsName::ISEA3H,
        tool: DggrsImplementation::DGGRID,
        title: "",
        description: "",
        uri: "",
        crs: "",
        aperture: 3,
        min_refinement_level: RefinementLevel::new_const(1),
        max_refinement_level: RefinementLevel::new_const(36),
        default_refinement_level: RefinementLevel::new_const(3),
        max_relative_depth: RelativeDepth::new_const(8),
        default_relative_depth: RelativeDepth::new_const(5),
    },
    DggrsSpec {
        id: DggrsUid::IGEO7,
        name: DggrsName::IGEO7,
        tool: DggrsImplementation::DGGRID,
        title: "",
        description: "",
        uri: "",
        crs: "",
        aperture: 7,
        min_refinement_level: RefinementLevel::new_const(0),
        max_refinement_level: RefinementLevel::new_const(20),
        default_refinement_level: RefinementLevel::new_const(2),
        max_relative_depth: RelativeDepth::new_const(5),
        default_relative_depth: RelativeDepth::new_const(3),
    },
    DggrsSpec {
        id: DggrsUid::H3,
        name: DggrsName::H3,
        tool: DggrsImplementation::H3O,
        title: "",
        description: "",
        uri: "",
        crs: "",
        aperture: 7,
        min_refinement_level: RefinementLevel::new_const(0),
        max_refinement_level: RefinementLevel::new_const(16),
        default_refinement_level: RefinementLevel::new_const(2),
        max_relative_depth: RelativeDepth::new_const(6),
        default_relative_depth: RelativeDepth::new_const(4),
    },
    DggrsSpec {
        id: DggrsUid::ISEA3HDGGAL,
        name: DggrsName::ISEA3H,
        tool: DggrsImplementation::DGGAL,
        title: "",
        description: "",
        uri: "",
        crs: "",
        aperture: 3,
        min_refinement_level: RefinementLevel::new_const(0),
        max_refinement_level: RefinementLevel::new_const(33),
        default_refinement_level: RefinementLevel::new_const(3),
        max_relative_depth: RelativeDepth::new_const(11),
        default_relative_depth: RelativeDepth::new_const(8),
    },
    DggrsSpec {
        id: DggrsUid::IVEA3H,
        name: DggrsName::IVEA3H,
        tool: DggrsImplementation::DGGAL,
        title: "",
        description: "",
        uri: "",
        crs: "",
        aperture: 3,
        min_refinement_level: RefinementLevel::new_const(0),
        max_refinement_level: RefinementLevel::new_const(33),
        default_refinement_level: RefinementLevel::new_const(3),
        max_relative_depth: RelativeDepth::new_const(11),
        default_relative_depth: RelativeDepth::new_const(8),
    },
    DggrsSpec {
        id: DggrsUid::ISEA9R,
        name: DggrsName::ISEA9R,
        tool: DggrsImplementation::DGGAL,
        title: "",
        description: "",
        uri: "",
        crs: "",
        aperture: 9,
        min_refinement_level: RefinementLevel::new_const(0),
        max_refinement_level: RefinementLevel::new_const(16),
        default_refinement_level: RefinementLevel::new_const(2),
        max_relative_depth: RelativeDepth::new_const(5),
        default_relative_depth: RelativeDepth::new_const(8),
    },
    DggrsSpec {
        id: DggrsUid::IVEA9R,
        name: DggrsName::IVEA9R,
        tool: DggrsImplementation::DGGAL,
        title: "",
        description: "",
        uri: "",
        crs: "",
        aperture: 9,
        min_refinement_level: RefinementLevel::new_const(0),
        max_refinement_level: RefinementLevel::new_const(16),
        default_refinement_level: RefinementLevel::new_const(2),
        max_relative_depth: RelativeDepth::new_const(5),
        default_relative_depth: RelativeDepth::new_const(8),
    },
    DggrsSpec {
        id: DggrsUid::RTEA3H,
        name: DggrsName::RTEA3H,
        tool: DggrsImplementation::DGGAL,
        title: "",
        description: "",
        uri: "",
        crs: "",
        aperture: 3,
        min_refinement_level: RefinementLevel::new_const(0),
        max_refinement_level: RefinementLevel::new_const(33),
        default_refinement_level: RefinementLevel::new_const(2),
        max_relative_depth: RelativeDepth::new_const(13),
        default_relative_depth: RelativeDepth::new_const(11),
    },
    DggrsSpec {
        id: DggrsUid::RTEA9R,
        name: DggrsName::RTEA9R,
        title: "",
        description: "",
        uri: "",
        crs: "",
        tool: DggrsImplementation::DGGAL,
        aperture: 9,
        min_refinement_level: RefinementLevel::new_const(0),
        max_refinement_level: RefinementLevel::new_const(16),
        default_refinement_level: RefinementLevel::new_const(2),
        max_relative_depth: RelativeDepth::new_const(5),
        default_relative_depth: RelativeDepth::new_const(8),
    },
    DggrsSpec {
        id: DggrsUid::IVEA7H,
        name: DggrsName::IVEA7H,
        tool: DggrsImplementation::DGGAL,
        title: "",
        description: "",
        uri: "",
        crs: "",
        aperture: 7,
        min_refinement_level: RefinementLevel::new_const(0),
        max_refinement_level: RefinementLevel::new_const(20),
        default_refinement_level: RefinementLevel::new_const(2),
        max_relative_depth: RelativeDepth::new_const(8),
        default_relative_depth: RelativeDepth::new_const(6),
    },
    DggrsSpec {
        id: DggrsUid::IVEA7H_Z7,
        name: DggrsName::IVEA7H_Z7,
        tool: DggrsImplementation::DGGAL,
        title: "",
        description: "",
        uri: "",
        crs: "",
        aperture: 7,
        min_refinement_level: RefinementLevel::new_const(0),
        max_refinement_level: RefinementLevel::new_const(20),
        default_refinement_level: RefinementLevel::new_const(2),
        max_relative_depth: RelativeDepth::new_const(8),
        default_relative_depth: RelativeDepth::new_const(6),
    },
];
